6일차
day06

0. 복습

넘파이
 : 수치 연산을 빠르게 하기 위한 라이브러리

1) 넘파이 배열 생성
 : np.array(리스트)

2) 배열의 속성
- 배열.shape
- 배열.ndim
- 배열.dtype
- 배열.size

3) 배열 생성 함수
- np.zeros((행, 열))
- np.ones((행, 열))
- np.arange(시작, 끝, 간격)
- np.linspace(시작, 끝, 개수)
- .reshape(행, 열)

4) 무작위 배열
- np.random.randint(시작, 끝, 개수)
- np.random.rand(개수)
- np.random.seed(숫자)

5) 불린 인덱싱 : 조건에 맞는 값만 가져오기
 : 배열[배열 > 값]

6) 조건으로 값 수정
 : np.where(조건, 참일때 값, 거짓일때 값)

7) 브로드캐스팅
 : 서로 크기가 다른 배열을 연산하기 위한 기능 
- 배열 + 값 => 모든 요소에 연산됨
- 배열 + 배열 => 같은 자리의 위치끼리 연산됨
- 2차원 배열 + 1차원 배열 => 1차원 배열이 2차원 배열의 각 행에
					연산됨

1) 넘파이

1) 집계함수
 : 배열 전체를 하나의 값으로 요약하는 함수들
함수			기능
=====================================================
.sum()			합계
.max()	/min()		최대 / 최소값
.mean()		평균
.std()			표준편차(흩어진 정도)

2) 행별/열별 집계
 : 2차원 데이터에서는 "전체 평균"보다
   "특성별 평균", "샘플별 평균"이 필요할 때가 많다
- axis 속성으로 계산 방향을 정한다
	axis = 0 : (기본값) => 결과는 열마다
	axis = 1 : 결과는 행마다

3) 최대값/최소값의 "위치" 찾기
- 배열.argmax() : 가장 큰 값이 위치한 위치 인덱스 번호 
- 배열.argmin() : 가장 작은 값이 위치한 위치 인덱스 번호

2. pands
 : 표 형태의 데이터를 다루는 라이브러리
- 데이터를 가공할때 많이 사용됨
- 판다스에서는 2개의 데이터 형태가 있다 
	Series : 인덱스(라벨)가 붙은 1차원 데이터
	DataFrame : 행과 열의 인덱스가 2차원 데이터

3. 시리즈(Series)
 : 값(데이터)들이 일렬로 늘어서 있고, 각 값마다 이름표(인덱스)가
   붙어 있는 1차원 데이터
- 넘파이 배열은 위치(0, 1, ...)로만 값을 다뤘지만, 
  "이 값이 무엇에 대한 것인지"이름이 필요하다
  ex) 90은 그냥 90이 아니라 "국어" 90점
- 시리즈 = 넘파이 배열 + 인덱스(이름)

1) 시리즈는 크게 3가지로 구성된다
- 인덱스(index) : 각 값의 이름표
- 값(values) : 실제 데이터, 내부적으로는 넘파이 배열
- 열(name) : 열의 이름

2) 시리즈의 생성
- import pandas as pd : pandas import
- pd.Series(데이터, index=인덱스, name=열이름)

3) 시리즈의 데이터 접근 
(1) 이름(라벨)로 접근
- 시리즈[라벨]
- 시리즈.loc[라벨]

(2) 위치 인덱스 번호 사용
- 시리즈.iloc[idx]

4) 시리즈 연산
- 넘파이 처럼 브로드캐스팅이 그대로 된다
- 연산 후에도 인덱스는 그대로 유지된다
- 두 시리즈를 연산하면 같은 인덱스(라벨)끼리 자동으로 맞춰
  계산된다. 짝이 없는 인덱스는 NaN(결측치)이 된다

5) 조건 필터링
 : 조건에 맞는 데이터를 선택할 때 사용
- 넘파이의 불린 인덱싱이 그대로 통한다
- sr > 값 : 참/거짓 으로 구성된 시리즈
- sr[sr > 값] : 조건에 맞는 값만 선택한다 

6) 통계 함수 및 메소드

메소드		기능
=========================================
.count()		값의 개수(NaN 제외)
.sum()			합계
.mean()		평균
.median()		중앙값(크기순 정렬 시 한가운데 값)
.std()			표준편차
.max()/main()	최대/최소 값
.mode()		최빈값(가장 자주 나온 값)
.describe()		통계들을 한번에 요약

## 넘파이
### 집계 함수

In [ ]:
import numpy as np
# 1차원 배열

arr = np.array([10, 20, 30, 40, 50])
print(arr)

print(f"합계 : {arr.sum()}")
print(f"평균 : {arr.mean()}")
print(f"최대값 : {arr.max()}")
print(f"최소값 : {arr.min()}")
print(f"표준편차 : {arr.std()}")
# 2차원 배열

# 학생 3명 x (국어, 영어) 점수
scores = np.array([[90, 80],
                  [70, 60],
                  [100, 50]])
print(scores)

print("==== 집계 함수 ====")
print(scores.sum()) # axis 없음 -> 전체 합계
print(scores.mean(axis=0)) # 열별(과목별) 평균 -> [국어 평균 영어 평균]
print(scores.mean(axis=1)) # 행별(학생별) 평균

### 최대 / 최소 값 위치 찾기

In [ ]:
arr = np.array([3, 7, 2, 9, 5])

print(f"최대값 : {arr.max()}")
print(f"최대값 위치 : {arr.argmax()}") # 3번 인덱스
print(f"최소값 위치 : {arr.argmin()}") # 2번 인덱스
# 분류 모델은 "각 정답일 확률"을 배열로 가져온다
# ex) [0.1 0.7 0.2]면 argmax()로 가장 확률 높은 위치(1번)을 골라
# "이 데이터는 1번 종류다"라고 예측한다

pred = np.array([0.1, 0.7, 0.2])
print(f"예측 : {pred.argmax()}번")
# <넘파이 배열 실습>
# 1) 2차원 배열(학생 3명의 국어, 영어) 
#  첫번째 학생 : 국어 80점, 영어 90점
# 두번째 학생 : 국어 70점, 영어 60점
# 세번째 학생 : 국어 100점, 영어 85점
# 과목별 평균과 학생별 평균을 출력

data = np.array([[80, 90],
                [70, 60],
                [100,85]])

print(f"전체 평균 : {data.mean() : .2f}")
print(f"과목별 평균 : {data.mean(axis=0).round(2)}")
print(f"학생별 평균 : {data.mean(axis=1)}")

## 시리즈(Series)

In [ ]:
import pandas as pd

# 시리즈 생성
sr1 = pd.Series([10, 20, 30, 40])
print(sr1)
# 인덱스를 설정하지 않으면 0부터 자동으로 붙는다

# index로 각 값에 이름(라벨)을 붙인다

sr2 = pd.Series([90, 85, 95], index=["국어", "영어", "수학"], name="학생1")
print(sr2)
# 시리즈의 구조
# : '인덱스', '값(데이터)', '열이름'으로 구성됨
print(sr2.index) # 인덱스(이름표)들
print(sr2.values, type(sr2.values)) # 데이터 => 넘파이 배열 형태
print(sr2.name) # 열이름
print(sr2.dtype) # 값들의 자료형

### 시리즈 데이터 접근

In [ ]:
# 시리즈 생성
sr = pd.Series([90, 85, 95], index=["국어", "영어", "수학"])
print(sr)

# 1) 이름(라벨) 사용
print("="*10)
print(sr.loc["국어"])
print(sr["국어"])
# 2) 위치 인덱스 번호
print(sr.iloc[0])
# 3) 여러개를 리스트로 골라 가져오기
print(sr[["국어", "수학"]])

# 4) 슬라이싱(이름(라벨)으로 슬라이싱은 "끝"도 포함한다!)
print(sr["국어" : "영어"])

# +) 위치 슬라이싱([0:2])은 끝을 포함하지 않지만,
#    이름 슬라이싱(["국어":"영어"])은 끝을 포함한다!

### 시리즈 연산

In [ ]:
print(sr)

# 벡터 연산(개별 값과 연산)
print("="*10)
print(sr + 5) # 모든 값에 5가 더해짐(인덱스 유지됨)
print(sr * 2)
# 시리즈 + 시리즈
sr_a = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
sr_b = pd.Series([10, 20, 30], index=['b', 'c', 'd'])

print(sr_a)
print(sr_b)
print("="*10)

print(sr_a + sr_b)  # b, c만 짝이 맞음. a, d는 짝이 없어 NaN
# NaN(Not a Number) : 결측치(결측값) => 빠져 있는 데이터

# 라벨(이름) 기준으로 자동 정렬되는 것이 pandas의 장점
# : 순서가 뒤섞인 데이터도 이름만 맞으면 알아서 짝지어서 계산한다

### 조건 필터링

In [ ]:
sr = pd.Series([90, 85, 95, 100, 70],
              index=["국어", "영어", "수학", "과학", "사회"])
print(sr)

print("="*10)
# 1) 90점 이상인 과목만
# print(sr >= 90) # 조건에 맞으면 True, 아니면 False가 들어간 시리즈
print(sr[sr >= 90])
# 2) 조건이 여러개인 경우
# & (and)
# / (or)

# 점수가 90점 이상 이거나(or) 80점 미만인 과목만
print(sr[(sr >= 90) | (sr < 80)])

### 시리즈 통계

In [ ]:
scores = pd.Series([85, 90, 78, 92, 88, 76])

print(f"개수 : {scores.count()}")
print(f"중앙값 : {scores.median()}")
# 데이터가 짝수일때, 가운데 2개의 값의 평균
print("="*10)
print(scores.describe())
fruits = pd.Series(["사과", "바나나", "사과", "포도", "바나나", "사과"])

# +) value_counts() : 각 값이 몇번 나오는지 센 다음,
# 데이터가 많은 순으로 정렬
print(fruits.value_counts())
print(f"최빈값 : {fruits.mode()[0]}")
# +) sort_values() : 값 기준으로 오름차순 정렬한다
#    ascending=False 옵션 설정으로 하면 내림차순 정렬을 한다

print(sr)

print("=== 오름차순 정렬 ===")
print(sr.sort_values())

print("=== 내림차순 정렬 ===")
print(sr.sort_values(ascending=False))
import numpy as np
# +) 결측값 : 결측지, 비어 있는 값, NaN으로 표현

# 결측값이 포한된 시리즈 생성
sr_nan = pd.Series([10, np.nan, 30, np.nan, 50])
# np.nan => 결측치
print(sr_nan)
# 결측치가 포함된 시리즈로 통계 메소드 사용
print(f"평균 : {sr_nan.mean()}") # 통계 함수는 NaN은 빼고 계산한다
# => 평균은 10, 30, 50의 평균 => 30
# <시리즈 실습>
# 1) 점수를 저장한 시리즈 생성 후
# 점수 : 88, 92, 45, 70, 95
# 80점 이상인 값만 필터링 후 출력, 평균도 출력 

scores = pd.Series([88, 92, 45, 70, 95])
print(scores[scores >= 80])
print(f"평균 : {scores.mean()}")
# 2) 위 시리즈를 점수가 높은 순으로 정렬 후 출력(내림차순 정렬)
print(scores.sort_values(ascending=False))
# 3) 색상이 저장된 시리즈 생성 후
# 색상 : 빨강, 파랑, 빨강, 초록, 파랑, 빨강
# 각 색이 몇 번 나오는지 출력, 최빈값도 출력

colors = pd.Series(["빨강", "파랑", "빨강", "초록", "파랑", "빨강"])
print(colors.value_counts())
print(f"최빈값 : {colors.mode()[0]}")

## 과제

## 문제 1) 불리언 인덱싱 — 조건에 맞는 값만 거르기

- 배열 `[42, 8, 19, 55, 3, 27, 60]` 에서 아래를 각각 출력하세요.
    1. **20 이상인 값만** 걸러 출력하고, **그 개수**도 출력하기 (힌트 : `배열[조건]`, `.size`)
    2. **10보다 크고(and) 50보다 작은** 값만 걸러 출력하기 (힌트 : `(조건1) & (조건2)`)
- 먼저 `import numpy as np` 가 필요합니다.

        <출력결과>
        [42 55 27 60]
        20 이상인 값의 개수 : 4
        [42 19 27]

In [ ]:
import numpy as np
arr = np.array([42, 8, 19, 55, 3, 27, 60])
print(arr[arr >= 20])
print(f"20 이상인 값의 개수 : {arr[arr >= 20].size}")
print(arr[(arr > 10) & (arr < 50)])

## 문제 2) 브로드캐스팅 — 모양이 달라도 맞춰 계산하기

1. 배열 `[100, 200, 300, 400]` 에 대해 **`+ 50`** 한 결과와 **`/ 100`** 한 결과를 각각 출력하세요.
2. 2차원 배열 `[[1, 2, 3], [4, 5, 6]]` 에 1차원 배열 `[10, 20, 30]` 을 **더한** 결과를 출력하세요.
(1차원 배열이 각 행에 열끼리 맞춰 더해집니다.)

        <출력결과>
        [150 250 350 450]
        [1. 2. 3. 4.]
        [[11 22 33]
         [14 25 36]]

In [ ]:
arr = np.array([100, 200, 300, 400])
print(arr + 50)
print(arr / 100)
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1 + np.array([10, 20, 30]))

## 문제 3) 집계 함수 — 데이터 요약하기

- 배열 `[23, 45, 12, 67, 34]` 의 **합계·평균·최댓값·최솟값·표준편차**를 각각 아래 형태로 출력하세요.
(힌트 : `.sum()`, `.mean()`, `.max()`, `.min()`, `.std()`)

        <출력결과>
        합계 : 181
        평균 : 36.2
        최댓값 : 67
        최솟값 : 12
        표준편차 : 18.925115587493778

In [ ]:
arr = np.array([23, 45, 12, 67, 34])
print(f"합계 : {arr.sum()}")
print(f"평균 : {arr.mean()}")
print(f"최댓값 : {arr.max()}")
print(f"최솟값 : {arr.min()}")
print(f"표준편차 : {arr.std()}")

## 문제 4) axis — 행별 / 열별로 집계하기

- 아래 2차원 배열(학생 3명 × 수학·과학 점수)에서 **과목별 평균**과 **학생별 평균**을 출력하세요.
    - **과목별 평균**은 `axis=0`(세로로 눌러 합침 → 열마다)
    - **학생별 평균**은 `axis=1`(가로로 눌러 합침 → 행마다)

        <데이터>
        [[80, 70],
         [90, 100],
         [60, 85]]

        <출력결과>
        과목별 평균 : [76.66666667 85.        ]
        학생별 평균 : [75.  95.  72.5]

In [ ]:
arr = np.array([[80, 70], [90, 100], [60, 85]])
print(f"과목별 평균 : {arr.mean(axis=0)}")
print(f"학생별 평균 : {arr.mean(axis=1)}")

## 문제 5) Series 만들기·조회·연산

- 리스트 `[120, 95, 140, 110]` (요일별 방문자 수)과 인덱스 `["월", "화", "수", "목"]` 으로 Series를 만들어 출력하세요.
- **"수"의 값**을 이름으로 꺼내 출력하세요.
- 모든 값에 **10을 더한** 결과를 출력하세요.
- 먼저 `import pandas as pd` 가 필요합니다.

        <출력결과>
        월    120
        화     95
        수    140
        목    110
        dtype: int64
        140
        월    130
        화    105
        수    150
        목    120
        dtype: int64

In [ ]:
import pandas as pd
sr = pd.Series([120, 95, 140, 110], index=["월", "화", "수", "목"])
print(sr)
print(sr.loc["수"])
print(sr + 10)

## 문제 6) 조건 필터링과 정렬

- Series `pd.Series([28, 33, 19, 25, 31], index=["서울","대구","강릉","부산","광주"])` (도시별 기온)에서:
    1. **30 이상인 값만** 걸러 출력하기
    2. 기온이 **높은 순(내림차순)**으로 정렬해 출력하기 (힌트 : `sort_values`, `ascending=False`)

        <출력결과>
        대구    33
        광주    31
        dtype: int64
        대구    33
        광주    31
        서울    28
        부산    25
        강릉    19
        dtype: int64

In [ ]:
sr = pd.Series([28, 33, 19, 25, 31], index=["서울","대구","강릉","부산","광주"])
print(sr[sr >= 30])
print(sr.sort_values(ascending=False))

## 문제 7) value_counts와 통계

1. Series `pd.Series(["A","O","A","B","O","O","AB"])` (혈액형)에서 **각 값이 몇 번 나오는지** 세어 출력하기 (`value_counts`)
2. Series `pd.Series([85, 90, 78, 92, 88, 76])` (점수)의 **평균·중앙값**을 출력하고, `describe()` 로 통계 요약을 한 번에 출력하기

        <출력결과>
        O     3
        A     2
        B     1
        AB    1
        Name: count, dtype: int64
        평균 : 84.83333333333333
        중앙값 : 86.5
        count     6.000000
        mean     84.833333
        std       6.524314
        min      76.000000
        25%      79.750000
        50%      86.500000
        75%      89.500000
        max      92.000000
        dtype: float64

In [ ]:
sr = pd.Series(["A","O","A","B","O","O","AB"])
print(sr.value_counts())
sr1 = pd.Series([85, 90, 78, 92, 88, 76])
print(f"평균 : {sr1.mean()}")
print(f"중앙값 : {sr1.median()}")
print(sr1.describe())