5일차
day05

1. 파일 입출력
 : 파일에 데이터를 작성(출력), 파일에서 데이터를 읽는(입력) 것

1) 파일 열기와 모드
- 파일을 다루려면 open()으로 연다
- 이때, 어떤 목적(모드)으로 열지 지정한다.
- open(파일명, 모드)
	모드			의미
==================================================
	"r"			읽기(read)		내용을 읽는다. 파일이 없으면 오류
	"w"			쓰기(write)		새로 작성. 기존 내용은 지워짐
							(덮어쓰기)
	"a"			추가 작성(append) 기존 내용 뒤에 덧붙인다

2) 파일 경로
- 파일을 열 때, 그 파일이 어디에 있는지(경로)를 알려줘야 한다.
- 상대 경로 : 지금 작업 중인 폴더(현재 위치)를 기준으로 한 경로
	./ : 현재 위치
	../ : 상위 디렉터리(상위 폴더)
- 절대 경로 : 최상위 경로부터 작업 할 파일명 까지 작성
	C:\puh\ml_1900\workspace\test.txt

3) with문
- open()으로 연 파일은 close()로 닫아야 하는데, 깜빡하기 쉽다
- with문으로 쓰면 블록이 끝날때 파일이 자동 저장된다.

3) 파일 읽기
  메소드		반환하는 것				사용할 때
====================================================
  read()		파일 전체를 하나의 문자열로	통째로 읽을 때
  readlines()		모든 줄을 리스트로		줄 단위 작업이 필요

2. 넘파이(Numpy)
 : 숫자 배열을 빠르고 편하게 다루는 라이브러리
- 머신러닝은 결국 대량의 숫자 데이터를 계산하는 일이다
  이때 데이터는 보통 행 = 데이터 하나, 열=특징(특성, 속성)인 
  숫자 표(행렬)로 표현 된다 
- 파이썬 리스트로 이런 계산을 하면 느리고 불편하다.
  넘파이의 배열은 빠르고, 숫자 계산을 아주 간단한 코드로 처리한다
- pands(데이터 표)와 scikit-learn(머신러닝)도 내부적으로 넘파이
  배열을 쓴다 

1) 넘파이 배열 생성
- np.array(리스트) : 파이썬 리스트를 넘파이 배열로 변환한다 
- 2차원 이상의 배열을 생성 : 2차원 이상의 리스트 작성 

2) 배열의 속성
- 배열.shape	배열의 모양(구조)
			1차원의 경우 : (열의 개수, )
			2차원의 경우 : (행의 개수, 열의 개수)
- 배열.ndim		차원 수
- 배열.dtype		요소의 자료형 
- 배열.size		전체 요소 개수

3) 자주 쓰는 생성 함수 
 : 배열을 리스트 없이 바로 만들어 내는 함수들 

  함수				기능				ML에서 용도
===================================================
np.zeros((행, 열))		0으로 채운 배열 		값 초기화, 테스트
np.ones((행, 열))		1로 채운 배열		값 초기화, 테스트
np.arange(시작, 끝, 간격) 연속적인 숫자 배열	인덱스, 구간
np.linspace(시작, 끝, 개수) 구간을 똑같은		그래프 x축,
				간격으로 n등분		구간 분할
np.reshape(행, 열)		배열의 모양을 바꿈	1차원<->2차원

4) 무작위 배열
- 머신러닝에서는 데이터를 무작위로 섞거나 초기값을 무작위로 정하는
  일이 많다
- np.random.rand(개수) : 0 ~ 1 사이의 실수를 무작위로
- np.random.randint(시작, 끝, 개수) : 정수를 무작위로 
- np.random.seed(숫자) : 무작위의 시작점을 고정해
				 항상 같은 결과가 나오게 한다

5) 넘파이 배열 인덱스 번호 
 : 시퀀스 자료형(문자열, 리스트, ...)과 같다 
- 인덱싱 : 배열[idx]
- 슬라이싱 : 배열[시작idx : 끝idx : 간격]

6) 조건에 맞는 값만 가져오기(불린 인덱싱)
 : 넘파이 배열에 조건을 설정하면 각 요소가 True/False인
   배열이 나오고, 그걸로 조건에 맞는 값만 가져올 수 있다
- 배열 > 값 : 각 요소를 비교한 참/거짓 배열
- 배열[조건] : 참의 위치의 값만 골라낸다
- 조건 여러개일 경우 
	- & (and)
	- | (or)
	- ~ (not)
7) 조건으로 값 수정 
- 조건에 맞는 위치 값을 한꺼번에 바꿀 수도 있다
- np.where(조건, 참일때 값, 거짓일때 값) :
			조건에 따라 값을 골라 채운 새 배열을 만든다

8) 브로드캐스팅
- 구조가 달라도 계산할 수 있게 하는 기능 
- 모양이 다른 배열끼리 연산할때, 넘파이가 작은 쪽을 자동으로 늘려
  맞춰주는 기능

## 파일 입출력

In [ ]:
# 파일을 작성 : 쓰기('w')로 연다(한글 깨짐 방지 인코딩 설정)
f = open("memo.txt", "w", encoding="utf-8") # 파일 객체 생성
f.write("첫 번째 줄입니다")
f.close() # 파일 닫기

print("파일 작성 완료!")
# 주피터 노트북을 열어준 workspace에 파일이 저장됨
# 상대 경로/절대 경로 
# : memo 폴더에 txt파일 작성

# 1) 절대경로 
with open(r"C:\puh\ml_1900\memo\absolute.txt", "w", encoding="utf-8") as f :
    f.write("절대경로로 작성")
print("절대경로로 작성 완료!")
# 2) 상대경로
# 현재 내 위치(workspace) => 상위 폴더로 이동(ml_1900) => memo로 이동
with open("./../memo/relative.txt", "w", encoding="utf-8") as f :
    f.write("상대경로로 작성")

print("상대경로로 저장 완료!")
# 파일 쓰기 : write()
# write(문자열) : 문자열을 파일에 작성
# (줄바꿈은 자동이 아니므로 줄을 바꾸려면 \n을 직접 넣는다)

with open("./fruits.txt", "w", encoding="utf-8") as f :
    f.write("사과\n")
    f.write("바나나\n")
    f.write("포도\n")

print("텍스트 파일 작성 완료!")
# "a"모드 : 기존 내용 맨 뒤에 추가 
with open("./fruits.txt", "a", encoding="utf-8") as f :
    f.write("딸기\n")
print("추가 작성 완료!")
# 파일 읽기

# 1) read() : 파일 전체를 하나의 문자열로 읽어옴
with open("./fruits.txt", "r", encoding="utf-8") as f :
    print(f.read(), type(f.read()))
# 2) readlines() : 각 줄을 요소로 갖는 리스트로 읽는다
with open("./fruits.txt", "r", encoding="utf-8") as f :
    lines = f.readlines()
    print(lines, type(lines))
    for line in lines :
        print(line, end="")
# +) for문 : 파일을 한 줄씩 꺼내 처리한다
with open("./fruits.txt", "r", encoding="utf-8") as f :
    for line in f :
        print(line.strip()) # strip() : 불필요한 문자열 제거 메소드 
                            #    => 문자열을 지정하지 않으면 공백제거!

## 넘파이

In [ ]:
import numpy as np # 넘파이 import

# 넘파이 배열 생성
arr = np.array([1, 2, 3, 4, 5])

print(arr, type(arr)) # 1차원 넘파이 배열 
# 2차원 배열 
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print(arr) # 2행 3열 넘파이 배열 
# 리스트 vs 배열 (왜 배열을 쓰는가)

# 리스트, 넘파이 배열 생성
li = [1, 2, 3]
arr = np.array([1, 2, 3])
print(li, type(li))
print(arr, type(arr))

# 리스트 +, *
print(li + li) # 리스트 연결
print(li * 3) # 리스트 반복

print("="*10)

# 배열의 +, * (요소별 연산)
print(arr + arr) # 같은 자리끼리 연산됨
print(arr * 2) # 모든 요소에 연산됨
print(arr + 10)
# 수천, 수만개의 데이터에 똑같은 계산을 반복문 없이 한번에 적용할 수 있다
# => 벡터 연산이 "머신러닝 계산"의 핵심

## 넘파이 배열 속성

In [ ]:
# 1차원 넘파이 배열
arr = np.array([1, 2, 3, 4])

print(f"구조(모양) : {arr.shape}") # (4,) => 요소 4개 1차원 넘파이 배열
print(f"차원 : {arr.ndim}") # 1 => 1차원
print(f"자료형 : {arr.dtype}") # int => 정수
print(f"개수 : {arr.size}") # 4개

# +) 주의!
# - 하나의 배열은 모든 요소가 같은 자료형이다
print(np.array([1,2,3]).dtype) # 전부 정수
print(np.array([1,2,3.0]).dtype) # 전부 실수
# 정수 사이에 실수가 하나라도 섞이면 전체가 실수(float)로 통일된다
# 2차원 배열 : 데이터는 대부분 2차원 형태이다(행과 열이 있는 구조)
# 행 = 데이터 하나, 열 = 특성

# 학생 3명의 (키, 몸무게) 데이터 => 3행 2열
data = np.array([[170, 65],
                [160, 55],
                [180, 75]])
print(data)

print("="*10)
print(f"구조 : {data.shape}") # (3, 2) => 학생 3명, 특성 2개
print(f"차원 : {data.ndim}") # 2

# 배열은 인덱스 번호 사용하여 값을 꺼낼 수 있다
print(data[0]) # 0번 행 전체 => 첫번째 학생 
print(data[0, 1]) # 0번 행 1번 열 => 첫번째 학생의 몸무게 

### 자주 쓰는 배열 생성 함수

In [ ]:
# 1) 0 / 1로 채운 배열
print(np.zeros((2, 3))) # 2행 3열, 전부 0.0
print("-------------")
print(np.ones((3, 4))) # 3행 4열, 전부 1.0
# 2) arange()
print(np.arange(6)) # 0 ~ 5까지 1차원
print(np.arange(0, 10)) # 0 ~ 9까지 1차원
print(np.arange(0, 10, 2)) # 0 ~ 9까지 2씩 1차원

# 3) reshape
print("="*10)
print(np.arange(6).reshape(2, 3)) # 0 ~ 5 여섯개를 2행 3열로 재배치

# 4) linspace : 0 ~ 1까지 5개로 균등 분할
print("="*10)
print(np.linspace(0, 1, 5))

### 무작위 넘파이 배열

In [ ]:
np.random.seed(42) # 시드 고정

print(np.random.rand(3)) # 0 ~ 1 실수 3개
print(np.random.randint(1, 7, 5)) # 1 ~ 6 정수 5개(주사위 5번)

### 넘파이 배열 인덱스 사용

In [ ]:
# 1차원 넘파이 배열
arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(arr[0]) # idx 0번
print(arr[-1]) # 맨 뒤
print(arr[1:4]) # idx 1 ~ 3
print(arr[::2]) # 처음부터 끝까지 2씩 간격
# 2차원 넘파이 배열
# - 2차원 배열은 배열명[행, 열]
# - ':'은 전체를 의미한다 => arr[:, 열번호]는 "모든 행에서 그 열만"

data = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(data)
print("="*10)
print(data[0, 1]) # 0번 행 1번 열 => 2
print(data[1]) # 1번 행 전체
print(data[0:2, 1:3]) # 0 ~ 1번 행, 1 ~ 2번 열
print(data[:, 0]) # 전체 행에서 0번 열
print(data[[0, 2]]) # 0번 행과 2번행만 골라내기

### 불린 인덱싱(조건에 맞는 값만 가져오기)

In [ ]:
arr = np.array([15, 3, 22, 8, 40, 6])
print(arr)

# 1) 조건을 주면 요소마다 참/거짓 배열이 나온다
print(arr > 10)

# 2) 그 조건을 []안에 넣으면 참인 값만 걸러진다
print(arr[arr > 10])
# 5보다 크고(and) 30보다 작은 값만
print(arr[(arr > 5) & (arr < 30)])

## 조건으로 값 수정

In [ ]:
arr = np.array([-3, 5, -1, 8, -7, 2])

# 음수인 위치의 값을 전부 0으로 바꾸기
arr[arr < 0] = 0
print(arr)
scores = np.array([85, 42, 90, 60, 30])

# 60 이상이면 "합격", 아니면 "불합격"
result = np.where(scores >= 60, "합격", "불합격")
print(result)

### 브로드 캐스팅

In [ ]:
arr = np.array([10, 20, 30, 40])

print(arr + 5) # 모든 요소에 5씩 더하기
print(arr * 2) # 모든 요소에 2씩 곱하기
# 2차원 배열 + 1차원 배열 => 1차원 배열이 각행에 똑같이 적용된다
data = np.array([[1, 2, 3],
                [4, 5, 6]])

# [10, 20, 30]이 2차원 배열의 모든 행에 더해진다
print(data + np.array([10, 20, 30]))
print(data * 2)
# +)

students = np.array([[170, 65],
                    [160, 55],
                    [180, 75]])
print(students)
print("="*10)
# 1차원 배열 [170, 60]이 각 행의 (키, 몸무게)에 열끼리 맞춰 적용
print(students - np.array([170 , 60]))

# 정규화(스케일링)에서 브로드 캐스팅을 사용

## 과제

## 문제 1) 리스트를 파일에 한 줄씩 저장 — write()
리스트 movies 를 "movies.txt" 파일에 한 줄씩 저장하세요.
with 문과 encoding="utf-8" 을 사용하고, 저장이 끝나면 "저장 완료" 를 출력하세요.
  <데이터>
  movies = ["기생충", "인터스텔라", "타이타닉"]

  <출력결과>
  저장 완료

In [ ]:
movies = ["기생충", "인터스텔라", "타이타닉"]

with open("movies.txt", "w", encoding="utf-8") as f :
    for movie in movies :
        f.write(movie + "\n")
print("저장 완료")

## 문제 2) 파일 전체 읽기 — read()
문제 1에서 만든 "movies.txt" 를 읽기 모드로 열어, read() 로 전체 내용을 읽어 출력하세요.
  <출력결과>
  기생충
  인터스텔라
  타이타닉

In [ ]:
with open("movies.txt", "r", encoding="utf-8") as f :
    for movie in movies :
        print(movie)

## 문제 3) 줄 개수 세기와 번호 붙이기 — readlines()
"movies.txt" 를 readlines() 로 읽어, 영화가 총 몇 개인지 "영화는 총 O개입니다" 형태로 출력하세요. (len)
이어서 파일을 한 줄씩 읽으며 각 줄 앞에 번호를 붙여 "1번: 기생충" 형태로 출력하세요.
힌트 : 번호 변수를 1에서 시작해 += 1, 줄 끝 줄바꿈은 strip() 으로 제거
<출력결과>
영화는 총 3개입니다
1번: 기생충
2번: 인터스텔라
3번: 타이타닉

In [ ]:
with open("movies.txt", "r", encoding="utf-8") as f :
    lines = f.readlines()
    print(f"영화는 총 {len(lines)}개 입니다")

    num = 1
    for line in lines :
        print(f"{num}번 : {line}",  end='')
        num += 1

## 문제 4) 배열 만들기와 속성 확인 — shape · dtype · size
리스트 [25, 30, 15, 40, 35] (시간대별 판매량)을 NumPy 배열로 만드세요.
배열의 모양(shape)·자료형(dtype)·개수(size) 를 각각 아래처럼 출력하세요.
먼저 import numpy as np 가 필요합니다.
<출력결과>
모양 : (5,)
자료형 : int64
개수 : 5

In [ ]:
import numpy as np
arr = np.array([25, 30, 15, 40, 35])
print(f"모양 : {arr.shape}")
print(f"자료형 : {arr.dtype}")
print(f"개수 : {arr.size}")

## 문제 5) 벡터 연산 — 반복문 없이 한 번에 계산
배열 [10, 20, 30, 40] (네 과목 점수)에 대해 아래 두 계산 결과를 각각 출력하세요.
모든 요소에 + 5 (가산점)를 한 결과
모든 요소에 2 를 한 결과
두 배열 [1, 2, 3] 과 [100, 200, 300] 을 더한 결과(요소별 덧셈)도 출력하세요.
  <출력결과>
  [15 25 35 45]
  [20 40 60 80]
  [101 202 303]

In [ ]:
arr = np.array([10, 20, 30, 40])
print(arr + 5)
print(arr * 2)
print(np.array([1, 2, 3]) + np.array([100, 200, 300]))

## 문제 6) 2차원 배열 — 모양·차원과 값 꺼내기
아래 2차원 데이터(학생 3명의 국어·영어 점수)로 배열을 만드세요.
모양(shape)·차원(ndim) 을 출력하고, [2, 1] 위치(2번 행 1번 열)의 값을 꺼내 출력하세요.
  <데이터>
  [[90, 85],
   [70, 95],
   [88, 80]]

  <출력결과>
  모양 : (3, 2)
  차원 : 2
  80

In [ ]:
arr = np.array([[90, 85],
               [70, 95],
               [88, 80]])
print(f"모양 : {arr.shape}")
print(f"차원 : {arr.ndim}")
print(arr[2, 1])

## 문제 7) 생성 함수 — arange · reshape · linspace · zeros
np.arange 로 0부터 11까지(12개)의 배열을 만든 뒤, reshape 로 3행 4열로 바꿔 출력하세요.
np.linspace 로 0부터 10까지 5등분한 배열을 출력하세요.
np.zeros 로 2행 3열 0(영) 배열을 만들어 출력하세요.
 <출력결과>
 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]
 [ 0.   2.5  5.   7.5 10. ]
 [[0. 0. 0.]
  [0. 0. 0.]]

In [ ]:
print(np.arange(0, 12).reshape(3, 4))
print(np.linspace(0, 10, 5))
print(np.zeros((2, 3)))

## 문제 8) 무작위 배열 — seed 로 결과 고정
np.random.seed(0) 으로 무작위의 시작점을 고정한 뒤, 아래 두 가지를 출력하세요.
np.random.randint 로 1~6 정수 5개(주사위 5번)
np.random.rand 로 0~1 실수 3개
시드를 고정했기 때문에 몇 번을 실행해도 결과가 같아야 합니다.
  <출력결과>
  [5 6 1 4 4]
  [0.54488318 0.4236548  0.64589411]

In [ ]:
np.random.seed(0)
print(np.random.randint(1, 7, 5))
print(np.random.rand(3))